/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package baselivre.ui.commentaire;

import baselivre.ui.frame.InterfaceRoot;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CDI117
 */
public class ValidationCommentaire extends javax.swing.JInternalFrame {

    private String sqlConnection;
    private InterfaceRoot ir;
    private Connection connection;
    
    public ValidationCommentaire(InterfaceRoot ir) {
        initComponents();
        this.ir = ir;
        this.sqlConnection = ir.SqlConnexion();
        
        try { //Connexion BDD
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        } catch (ClassNotFoundException ex) {   
            JOptionPane.showMessageDialog(this, "Driver non trouvé ! "+ex.getMessage());
        }
        try {
            connection = DriverManager.getConnection(this.sqlConnection);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"erreur base de données "+ ex.getErrorCode());
        }
        
        
    }

    private DefaultTableModel initTable() {
        
        Vector c= new Vector();
        Vector l= new Vector();
        String query = "SELECT * FROM commentaire WHERE avis_actif=0 ORDER BY avis_date";
        try {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                //Commentaire c=new Commentaire(rs.getInt("id_acheteur"), rs.getInt("id_livre"),);
                //v.add(t);
                c.add(rs.getInt("id_acheteur"));
                c.add(rs.getInt("id_livre"));
                c.add(rs.getInt("avis_rating"));
                c.add(rs.getString("avis_texte"));
                c.add(rs.getString("avis_actif"));
                //c.add(rs.getDate("avis_date"));
                l.add(c);
            }
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQL ! "+ex.getMessage());
            return null;
        }
        Vector t= new Vector();
        t.add("Acheteur");
        t.add("Livre");
        t.add("Note");
        t.add("Commentaire");
        t.add("Date");
        t.add("Etat");
        DefaultTableModel tm= new DefaultTableModel(l,t);
        
        return tm;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(305, 305, 305))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jTable1.setModel(initTable());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
