package baselivre.ui.cdeaffichage;

import baselivre.produit.Editeur;
import baselivre.ui.frame.InterfaceRoot;
import baselivre.user.Acheteur;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author cdi107
 */
public class jiCdeAffichage extends javax.swing.JInternalFrame {
     private String sqlConnexion;
     private String nameSearch;
     private int idAcheteur;
     private int idCde;
  

    /**
     * Creates new form jiCdeAffichage
     * @param ir InterfaceRoot
     */
    public jiCdeAffichage(InterfaceRoot ir) {
        initComponents();
        this.sqlConnexion = ir.SqlConnexion();

    }
 private Vector initbaselivre() {
        Vector ach = new Vector();
return ach;
 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLAcheteur = new javax.swing.JLabel();
        jBAfficherDetail = new javax.swing.JButton();
        jBModifierCde = new javax.swing.JButton();
        jBSuppCde = new javax.swing.JButton();
        jtfAch_nom = new javax.swing.JTextField();
        jTFCdeNum = new javax.swing.JTextField();
        jTFCdeDate = new javax.swing.JTextField();
        jLNumCde = new javax.swing.JLabel();
        jLDteCde = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTCde = new javax.swing.JTable();
        jLInvit = new javax.swing.JLabel();
        jBSearchCde = new javax.swing.JButton();
        jRnom = new javax.swing.JRadioButton();
        jRadressMail = new javax.swing.JRadioButton();
        jRpseudo = new javax.swing.JRadioButton();
        jtSaisieAch = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Affichage Commande");
        getContentPane().setLayout(null);

        jLAcheteur.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLAcheteur.setText("Acheteur");
        getContentPane().add(jLAcheteur);
        jLAcheteur.setBounds(20, 0, 100, 30);

        jBAfficherDetail.setText("Afficher Détails");
        jBAfficherDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAfficherDetailActionPerformed(evt);
            }
        });
        getContentPane().add(jBAfficherDetail);
        jBAfficherDetail.setBounds(10, 380, 105, 23);

        jBModifierCde.setText("Modifier");
        getContentPane().add(jBModifierCde);
        jBModifierCde.setBounds(130, 380, 71, 23);

        jBSuppCde.setText("Supprimer");
        getContentPane().add(jBSuppCde);
        jBSuppCde.setBounds(220, 380, 81, 23);

        jtfAch_nom.setText("nom acheteur");
        getContentPane().add(jtfAch_nom);
        jtfAch_nom.setBounds(10, 170, 146, 31);
        getContentPane().add(jTFCdeNum);
        jTFCdeNum.setBounds(130, 110, 220, 40);

        jTFCdeDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCdeDateActionPerformed(evt);
            }
        });
        getContentPane().add(jTFCdeDate);
        jTFCdeDate.setBounds(470, 110, 180, 40);

        jLNumCde.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLNumCde.setText("N° de Commande");
        getContentPane().add(jLNumCde);
        jLNumCde.setBounds(20, 130, 110, 10);

        jLDteCde.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLDteCde.setText("Date Commande");
        getContentPane().add(jLDteCde);
        jLDteCde.setBounds(360, 120, 120, 20);

        jTCde.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTCde);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 220, 687, 97);

        jLInvit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLInvit.setText("Saisissez un des critères de recherche");
        getContentPane().add(jLInvit);
        jLInvit.setBounds(240, 10, 206, 15);

        jBSearchCde.setText("Rechercher");
        jBSearchCde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSearchCdeActionPerformed(evt);
            }
        });
        getContentPane().add(jBSearchCde);
        jBSearchCde.setBounds(600, 40, 100, 40);

        buttonGroup1.add(jRnom);
        jRnom.setText("Nom");
        jRnom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRnomActionPerformed(evt);
            }
        });
        getContentPane().add(jRnom);
        jRnom.setBounds(40, 30, 43, 20);

        buttonGroup1.add(jRadressMail);
        jRadressMail.setText("Adress @mail");
        getContentPane().add(jRadressMail);
        jRadressMail.setBounds(40, 50, 89, 20);

        buttonGroup1.add(jRpseudo);
        jRpseudo.setText("Pseudo");
        jRpseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRpseudoActionPerformed(evt);
            }
        });
        getContentPane().add(jRpseudo);
        jRpseudo.setBounds(40, 80, 61, 20);

        jtSaisieAch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jtSaisieAch);
        jtSaisieAch.setBounds(130, 40, 460, 40);

        getAccessibleContext().setAccessibleName("CdeAffichage");

        setBounds(0, 0, 723, 453);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAfficherDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAfficherDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAfficherDetailActionPerformed

    private void jTFCdeDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCdeDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCdeDateActionPerformed

    private void jRpseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRpseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRpseudoActionPerformed

    private void jBSearchCdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSearchCdeActionPerformed
              try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        } catch (ClassNotFoundException ex) {
            JOptionPane jErreur = new JOptionPane(" Driver non trouvé : " + ex.getMessage());
        }

        Connection connexion = null;
        try {
            connexion = DriverManager.getConnection(sqlConnexion);
        } catch (SQLException ex) {
            JOptionPane jErreur = new JOptionPane("Erreur connexion Base de donnees"
                    + ex.getErrorCode()
                    + ":" + ex.getMessage());
        }
        ResultSet rs = null;
        ResultSet rs2 = null;
        try {  
           String sql=null;
           String sqlAch = null;
            Statement stmt = connexion.createStatement();
            if(!jtSaisieAch.getText().equals("")){
                if(jRnom.isSelected()){
                    rs2 = stmt.executeQuery("SELECT * from acheteur WHERE ach_nom LIKE '%"+jtSaisieAch.getText()+"%'");
                    idAcheteur = rs2.getInt("id_acheteur");
                    if(!jTFCdeNum.getText().equals("")){
                        if(!jTFCdeDate.getText().equals("")){
                            sql = "Select * from commande where id_acheteur = "+idAcheteur+" "
                                    + " AND cde_numcommande LIKE '%"+jTFCdeNum.getText()+"%' AND cde_date LIKE '%"+jTFCdeDate.getText()+"%'";
                        }else{
                            sql = "Select * from commande where id_acheteur = "+idAcheteur+" "
                                    + " AND cde_num LIKE '%"+jTFCdeNum.getText()+"%'";
                        }
                    }else{
                        if(!jTFCdeDate.getText().equals("")){
                            sql = "Select * from commande where id_acheteur = "+idAcheteur+" "
                                    + " AND cde_date LIKE '%"+jTFCdeDate.getText()+"%'";
                        }else{
                            sql = "Select * from commande where id_acheteur = "+idAcheteur;
                        }
                    }
                            
                }else if (jRadressMail.isSelected()){
                    rs2 = stmt.executeQuery("SELECT * from acheteur WHERE ach_email LIKE '%"+jtSaisieAch.getText()+"%'");
                    idAcheteur = rs2.getInt("id_acheteur");
                    if(!jTFCdeNum.getText().equals("")){
                        if(!jTFCdeDate.getText().equals("")){
                            sql = "Select * from commande where id_acheteur = "+idAcheteur+" "
                                    + " AND cde_num LIKE '%"+jTFCdeNum.getText()+"%' AND cde_date LIKE '%"+jTFCdeDate.getText()+"%'";
                        }else{
                            sql = "Select * from commande where id_acheteur = "+idAcheteur+" "
                                    + " AND cde_num LIKE '%"+jTFCdeNum.getText()+"%'";
                        }
                    }else{
                        if(!jTFCdeDate.getText().equals("")){
                            sql = "Select * from commande where id_acheteur = "+idAcheteur+" "
                                    + " AND cde_date LIKE '%"+jTFCdeDate.getText()+"%'";
                        }else{
                            sql = "Select * from commande where id_acheteur = "+idAcheteur;
                        }
                    }
                }else{
                    rs2 = stmt.executeQuery("SELECT * from acheteur WHERE ach_pseudo LIKE '%"+jtSaisieAch.getText()+"%'");
                    idAcheteur = rs2.getInt("id_acheteur");
                    if(!jTFCdeNum.getText().equals("")){
                        if(!jTFCdeDate.getText().equals("")){
                            sql = "Select * from commande where id_acheteur = "+idAcheteur+" "
                                    + " AND cde_num LIKE '%"+jTFCdeNum.getText()+"%' AND cde_date LIKE '%"+jTFCdeDate.getText()+"%'";
                        }else{
                            sql = "Select * from commande where id_acheteur = "+idAcheteur+" "
                                    + " AND cde_num LIKE '%"+jTFCdeNum.getText()+"%'";
                        }
                    }else{
                        if(!jTFCdeDate.getText().equals("")){
                            sql = "Select * from commande where id_acheteur = "+idAcheteur+" "
                                    + " AND cde_date LIKE '%"+jTFCdeDate.getText()+"%'";
                        }else{
                            sql = "Select * from commande where id_acheteur = "+idAcheteur;
                        }
                    }
                }
            }else{
                if(!jTFCdeNum.getText().equals("")){
                    if(!jTFCdeDate.getText().equals("")){
                        sql = "SELECT * from commande where cde_num LIKE '%"+jTFCdeNum.getText()+"%' AND cde_date LIKE '%"+jTFCdeDate.getText()+"%'";
                    }else{
                        sql ="SELECT * FROM commande WHERE cde_num LIKE '%"+jTFCdeNum.getText()+"%'";
                    }
                }else{
                    sql ="SELECT * from commande";
                }
            }
            
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                System.out.println(rs.getString("acheteur_nom"));
            }
            // liste de commande issue de la requete qui va alimenter le vecteur
            // pour la Jtable
            
//            while (rs.next()) {
//                Acheteur acht = new Acheteur(rs.getString("ach_nom"), rs.getString("ach_"), true);
////
//                ach.add(acheteur);
//            }
            rs.close();
            stmt.close();
//            return null;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur base de données : "+ex.getMessage());
//            return null;
        }
 
    }//GEN-LAST:event_jBSearchCdeActionPerformed

    private void jRnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRnomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAfficherDetail;
    private javax.swing.JButton jBModifierCde;
    private javax.swing.JButton jBSearchCde;
    private javax.swing.JButton jBSuppCde;
    private javax.swing.JLabel jLAcheteur;
    private javax.swing.JLabel jLDteCde;
    private javax.swing.JLabel jLInvit;
    private javax.swing.JLabel jLNumCde;
    private javax.swing.JRadioButton jRadressMail;
    private javax.swing.JRadioButton jRnom;
    private javax.swing.JRadioButton jRpseudo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTCde;
    private javax.swing.JTextField jTFCdeDate;
    private javax.swing.JTextField jTFCdeNum;
    private javax.swing.JTextField jtSaisieAch;
    private javax.swing.JTextField jtfAch_nom;
    // End of variables declaration//GEN-END:variables
}
