package baselivre.ui.editeur;


import baselivre.ui.frame.InterfaceRoot;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class jiEditeurCreation extends javax.swing.JInternalFrame {

    private String sqlConnexion;
    private InterfaceRoot ir;

    public jiEditeurCreation( InterfaceRoot ir) {
        this.ir=ir;
        this.sqlConnexion = ir.SqlConnexion();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Creer = new javax.swing.JButton();
        jtfnomEditeur = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        adresseEditeur = new javax.swing.JLabel();
        jtfadresseEditeur = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfcpEditeur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfvilleEditeur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfpaysEditeur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtftelEditeur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfemailEditeur = new javax.swing.JTextField();

        setResizable(true);
        setTitle("Creation  Editeur");
        setToolTipText("");
        getContentPane().setLayout(null);

        Creer.setText("Creer");
        Creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerActionPerformed(evt);
            }
        });
        getContentPane().add(Creer);
        Creer.setBounds(150, 220, 59, 23);

        jtfnomEditeur.setText(" ");
        jtfnomEditeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnomEditeurActionPerformed(evt);
            }
        });
        getContentPane().add(jtfnomEditeur);
        jtfnomEditeur.setBounds(110, 10, 170, 30);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton);
        CancelButton.setBounds(400, 220, 73, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 70, 15);

        adresseEditeur.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        adresseEditeur.setText("Adresse");
        adresseEditeur.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(adresseEditeur);
        adresseEditeur.setBounds(20, 60, 70, 20);

        jtfadresseEditeur.setText(" ");
        jtfadresseEditeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfadresseEditeurActionPerformed(evt);
            }
        });
        getContentPane().add(jtfadresseEditeur);
        jtfadresseEditeur.setBounds(110, 50, 170, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Code Postal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 70, 15);

        jtfcpEditeur.setText(" ");
        getContentPane().add(jtfcpEditeur);
        jtfcpEditeur.setBounds(110, 90, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ville");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 50, 15);

        jtfvilleEditeur.setText(" ");
        jtfvilleEditeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfvilleEditeurActionPerformed(evt);
            }
        });
        getContentPane().add(jtfvilleEditeur);
        jtfvilleEditeur.setBounds(110, 130, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Pays");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 180, 50, 15);

        jtfpaysEditeur.setText(" ");
        getContentPane().add(jtfpaysEditeur);
        jtfpaysEditeur.setBounds(110, 170, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Telephone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 30, 90, 30);

        jtftelEditeur.setText(" ");
        getContentPane().add(jtftelEditeur);
        jtftelEditeur.setBounds(380, 30, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("  e_mail @ :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 70, 100, 30);

        jtfemailEditeur.setText(" ");
        jtfemailEditeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfemailEditeurActionPerformed(evt);
            }
        });
        getContentPane().add(jtfemailEditeur);
        jtfemailEditeur.setBounds(380, 70, 150, 30);

        getAccessibleContext().setAccessibleName("EDITEUR Création");

        setSize(new java.awt.Dimension(597, 286));
    }// </editor-fold>//GEN-END:initComponents

    private void jtfnomEditeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnomEditeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnomEditeurActionPerformed

    private void jtfadresseEditeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfadresseEditeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfadresseEditeurActionPerformed

    private void jtfvilleEditeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfvilleEditeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfvilleEditeurActionPerformed

    /** Creation d'un nouvel "Editeur" dans la base SQL "baselivre"
     * Connexion a la base,
     * Insertion des attributs de la nouvelle entree,
     * Fermeture de la connexion
     * 
     * @param evt 
     */
    
    private void CreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this," Driver non trouvé : " + ex.getMessage());
        }

        Connection connexion = null;
        try {
            connexion = DriverManager.getConnection(sqlConnexion);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur connexion Base de donnees"
                    + ex.getMessage());
        }
        
            try {
            Statement stmt = connexion.createStatement();
            // recupere le nom saisi ds la champ Nom et verifier qu'il n'existe pas dans les inactifs.
//            String query = " SELECT * FROM editeur WHERE editeur_nom = '" + jtfnomEditeur.getText() + "'";
//            ResultSet rs = stmt.executeQuery(query);
//            ResultSetMetaData resultMeta = rs.getMetaData();

            
                  

            String sql = "INSERT INTO editeur (editeur_nom, editeur_adresse,"
                    + "editeur_cp,"
                    + "editeur_ville,"
                    + "editeur_pays,"
                    + "editeur_tel,"
                    + "editeur_email,"
                    + "editeur_actif) VALUES ('" + jtfnomEditeur.getText() + "',"
                    + "'" + jtfadresseEditeur.getText() + "','" + jtfcpEditeur.getText() + "'"
                    + ",'" + jtfpaysEditeur.getText() + "','" + jtftelEditeur.getText() + "','" + jtfemailEditeur.getText() + "',1)";

            int result = stmt.executeUpdate(sql);
//            rs.close();
            stmt.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur de saisie"
                    + ex.getMessage());
        }
        try {
        connexion.close();
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur de saisie"
                    + ex.getMessage());
            
        }

    }//GEN-LAST:event_CreerActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
  this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void jtfemailEditeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfemailEditeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfemailEditeurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton Creer;
    private javax.swing.JLabel adresseEditeur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtfadresseEditeur;
    private javax.swing.JTextField jtfcpEditeur;
    private javax.swing.JTextField jtfemailEditeur;
    private javax.swing.JTextField jtfnomEditeur;
    private javax.swing.JTextField jtfpaysEditeur;
    private javax.swing.JTextField jtftelEditeur;
    private javax.swing.JTextField jtfvilleEditeur;
    // End of variables declaration//GEN-END:variables
}
